server {
    listen 443 ssl;
#    server_name your.domain.com;

    ssl_certificate /etc/ssl/certs/nautilus.crt; # Path to your certificate bundle
    ssl_certificate_key /etc/ssl/private/nautilus.key; # Path to your private key

    # Optional: Recommended security settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    # ... other configurations
}
