---
- name: Install nginx
  ansible.builtin.package:
    name: "{{ nginx_package_name }}"
    state: "{{ nginx_state }}"
  become: true

- name: Ensure nginx is enabled and running
  ansible.builtin.service:
    name: "{{ nginx_service_name }}"
    enabled: "{{ nginx_enabled }}"
    state: started
  become: true

- name: Deploy nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx