---
- name: Prepare application nodes
  hosts: stapp02.stratos.xfusioncorp.com
  become: true

  tasks:
    - name: Install the latest version of nginx.
      ansible.builtin.package:
        name:
          - nginx
        state: latest

    - name: Ensure nginx is enabled and running
      ansible.builtin.service:
        name: nginx
        enabled: true
        state: started
      become: true

#    - name: Copy nginx config
#      ansible.builtin.copy:
#        src: files/nginx.conf
#        dest: /etc/nginx/nginx.conf
#      notify: Restart nginx

    - name: Ensure SSL directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop:
        - /etc/ssl/private
        - /etc/ssl/certs
      become: true

    - name: Copy private key
      ansible.builtin.copy:
        remote_src: true
        src: /tmp/nautilus.key
        dest: /etc/ssl/private/nautilus.key
        owner: root
        group: root
        mode: '0600'
      become: true

    - name: Copy certificate
      ansible.builtin.copy:
        remote_src: true
        src: /tmp/nautilus.crt
        dest: /etc/ssl/certs/nautilus.crt
        owner: root
        group: root
        mode: '0644'
      become: true

#  handlers:
#
#    - name: Restart nginx
#      ansible.builtin.service:
#        name: nginx
#        state: restarted
