all:
  children:
    app:
      hosts:
        stapp01.stratos.xfusioncorp.com:
        stapp02.stratos.xfusioncorp.com:
        stapp03.stratos.xfusioncorp.com:
    lb:
      hosts:
        stlb01:
    db:
      hosts:
        stdb01.stratos.xfusioncorp.com:
    storage:
      hosts:
        ststor01.stratos.xfusioncorp.com:
    backup:
      hosts:
        stbkp01.stratos.xfusioncorp.com:
    mail:
      hosts:
        stmail01.stratos.xfusioncorp.com:
    ci:
      hosts:
        jenkins.stratos.xfusioncorp.com: