all:
  children:
    app:
      hosts:
        stapp01:
        stapp02:
        stapp03:
    lb:
      hosts:
        stlb01:
    db:
      hosts:
        stdb01:
    storage:
      hosts:
        ststor01:
    backup:
      hosts:
        stbkp01:
    mail:
      hosts:
        stmail01:
    ci:
      hosts:
        jenkins: